# -*- coding: utf-8 -*-

# Generated by Django 5.2.12 on 2026-04-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('order_update', '订单更新'), ('task_assigned', '任务分配'), ('measurement_result', '量尺结果'), ('maintenance', '维修通知'), ('system', '系统通知'), ('inventory_alert', '库存预警')], default='system', max_length=30, verbose_name='通知类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(blank=True, default='', verbose_name='内容')),
                ('related_id', models.IntegerField(blank=True, null=True, verbose_name='相关业务ID')),
                ('related_type', models.CharField(blank=True, default='', max_length=50, verbose_name='相关业务类型')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='阅读时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
