# -*- coding: utf-8 -*-

# Generated by Django 5.2.12 on 2026-04-05 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分公司名称')),
                ('city', models.CharField(blank=True, default='', max_length=50, verbose_name='城市')),
                ('address', models.CharField(blank=True, default='', max_length=500, verbose_name='地址')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '分公司',
                'verbose_name_plural': '分公司',
                'db_table': 'branches',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='权限代码')),
                ('name', models.CharField(max_length=100, verbose_name='权限名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('resource', models.CharField(blank=True, default='', max_length=50, verbose_name='资源类型')),
                ('action', models.CharField(blank=True, default='', max_length=50, verbose_name='操作类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
                'db_table': 'permissions',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='角色名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='角色代码')),
                ('description', models.TextField(blank=True, default='', verbose_name='描述')),
                ('permissions', models.JSONField(blank=True, default=dict, verbose_name='权限配置')),
                ('is_system', models.BooleanField(default=False, verbose_name='是否系统内置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='手机号')),
                ('real_name', models.CharField(blank=True, default='', max_length=50, verbose_name='真实姓名')),
                ('wechat_open_id', models.CharField(blank=True, default='', max_length=128, unique=True, verbose_name='微信OpenID')),
                ('wechat_union_id', models.CharField(blank=True, default='', max_length=128, verbose_name='微信UnionID')),
                ('avatar', models.CharField(blank=True, default='', max_length=500, verbose_name='头像URL')),
                ('role', models.CharField(choices=[('system_admin', '系统管理员'), ('admin', '管理员'), ('clerk_wood', '文员-木门'), ('clerk_alloy', '文员-合金门'), ('clerk_security', '文员-防盗门'), ('warehouse', '仓库人员'), ('measurer', '量尺师傅'), ('installer', '安装师傅'), ('repairman', '维修师傅'), ('foreman', '工头')], default='installer', max_length=20, verbose_name='角色')),
                ('city', models.CharField(blank=True, default='', max_length=50, verbose_name='城市')),
                ('product_line', models.CharField(blank=True, choices=[('wood', '木门'), ('alloy', '合金门'), ('security', '防盗门')], default='', max_length=20, verbose_name='文员产品线')),
                ('status', models.CharField(choices=[('active', '在职'), ('resigned', '离职'), ('disabled', '禁用')], default='active', max_length=20, verbose_name='状态')),
                ('is_staff', models.BooleanField(default=False, verbose_name='员工')),
                ('is_active', models.BooleanField(default=True, verbose_name='激活')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='最后登录时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.branch', verbose_name='分公司')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
    ]
