# Generated by Django 5.2.12 on 2026-04-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('clerk', '文员'), ('warehouse', '仓库人员'), ('measurer', '量尺师傅'), ('installer', '安装师傅'), ('repairman', '维修师傅'), ('foreman', '工头')], default='installer', max_length=20, verbose_name='角色'),
        ),
    ]
