# -*- coding: utf-8 -*-

# Generated by Django 5.2.12 on 2026-04-06 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decoration', '0002_remove_brand_address_remove_store_city_and_more'),
        ('permissions', '0001_initial'),
        ('users', '0003_preset_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('decoration', '装企人员'), ('management', '管理人员'), ('service', '服务人员'), ('admin', '系统管理员')], default='decoration', max_length=20, verbose_name='用户类型')),
                ('department', models.CharField(blank=True, default='', max_length=50, verbose_name='所属部门')),
                ('status', models.CharField(choices=[('active', '正常'), ('pending', '待审核'), ('rejected', '已驳回'), ('disabled', '已禁用')], default='active', max_length=20, verbose_name='状态')),
                ('reject_reason', models.TextField(blank=True, default='', verbose_name='驳回原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='decoration.brand', verbose_name='装企品牌')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='permissions.role', verbose_name='角色')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='decoration.store', verbose_name='装企门店')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户档案',
                'verbose_name_plural': '用户档案',
                'db_table': 'user_profiles',
            },
        ),
    ]
