# -*- coding: utf-8 -*-

# Generated by Django 5.2.12 on 2026-04-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wechat_open_id',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, unique=True, verbose_name='微信OpenID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='wechat_union_id',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, verbose_name='微信UnionID'),
        ),
    ]
