# Generated by Django 5.2.12 on 2026-04-06 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_wechat_open_id_alter_user_wechat_union_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='identity',
            field=models.CharField(choices=[('decoration', '装企'), ('contractor', '乙方'), ('customer', '客户')], default='contractor', max_length=20, verbose_name='身份'),
        ),
    ]
