# Generated by Django 5.2.13 on 2026-04-22 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_role_user_identity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Role',
            new_name='UserRole',
        ),
        migrations.AlterModelOptions(
            name='userrole',
            options={'verbose_name': '角色(已废弃)', 'verbose_name_plural': '角色(已废弃)'},
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='请输入正确的11位手机号', regex='^1[3-9]\\d{9}$')], verbose_name='手机号'),
        ),
    ]
