# Generated by Django 5.2.13 on 2026-04-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_role_userrole_alter_userrole_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='identity',
            field=models.CharField(choices=[('decoration', '装企'), ('contractor', '乙方'), ('customer', '客户')], db_index=True, default='contractor', max_length=20, verbose_name='身份'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', '在职'), ('resigned', '离职'), ('disabled', '禁用')], db_index=True, default='active', max_length=20, verbose_name='状态'),
        ),
    ]
