# Generated by Django 5.2.12 on 2026-04-05 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoryInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='配件名称')),
                ('spec_model', models.CharField(blank=True, default='', max_length=200, verbose_name='规格型号')),
                ('current_stock', models.IntegerField(default=0, verbose_name='当前库存')),
                ('purchasing_quantity', models.IntegerField(default=0, verbose_name='采购中数量')),
                ('city', models.CharField(blank=True, default='', max_length=50, verbose_name='城市')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '配件仓',
                'verbose_name_plural': '配件仓',
                'db_table': 'accessory_inventory',
            },
        ),
        migrations.CreateModel(
            name='HardwareInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='五金名称')),
                ('hardware_type', models.CharField(help_text='木门/合金门/防盗门用', max_length=20, verbose_name='类型')),
                ('current_stock', models.IntegerField(default=0, verbose_name='当前库存')),
                ('alert_quantity', models.IntegerField(default=0, verbose_name='预警数量')),
                ('purchasing_quantity', models.IntegerField(default=0, verbose_name='采购中数量')),
                ('pending_out_quantity', models.IntegerField(default=0, help_text='确认后20天内订单', verbose_name='待出库需求量')),
                ('available_stock', models.IntegerField(default=0, verbose_name='可用库存')),
                ('city', models.CharField(blank=True, default='', max_length=50, verbose_name='城市')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '五金仓',
                'verbose_name_plural': '五金仓',
                'db_table': 'hardware_inventory',
            },
        ),
        migrations.CreateModel(
            name='PendingGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=200, verbose_name='货品名称/型号')),
                ('door_type', models.CharField(help_text='木门/合金门/防盗门', max_length=20, verbose_name='门种类')),
                ('spec_size', models.JSONField(blank=True, default=dict, help_text='详细拆分', verbose_name='规格尺寸')),
                ('color', models.CharField(blank=True, default='', max_length=50, verbose_name='颜色')),
                ('other_config', models.TextField(blank=True, default='', verbose_name='其他配置')),
                ('inbound_time', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
                ('inbound_reason', models.CharField(blank=True, default='', max_length=200, verbose_name='入库原因')),
                ('match_status', models.CharField(choices=[('unmatched', '未匹配'), ('matched', '已匹配')], default='unmatched', max_length=20, verbose_name='匹配状态')),
                ('matched_order_no', models.CharField(blank=True, default='', max_length=50, verbose_name='匹配订单号')),
                ('city', models.CharField(blank=True, default='', max_length=50, verbose_name='城市')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '货品暂存仓',
                'verbose_name_plural': '货品暂存仓',
                'db_table': 'pending_goods',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(db_index=True, max_length=50, verbose_name='订单号')),
                ('product_type', models.CharField(help_text='木门/合金门/防盗门', max_length=20, verbose_name='产品类型')),
                ('product_model', models.CharField(blank=True, default='', max_length=100, verbose_name='产品型号')),
                ('lock_model', models.CharField(blank=True, default='', max_length=100, verbose_name='锁具型号')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('status', models.CharField(choices=[('pending_ship', '待发货'), ('shipped', '已发货'), ('arrived', '已到货'), ('pending_deliver', '待派送'), ('delivered', '已派送')], default='pending_ship', max_length=20, verbose_name='状态')),
                ('logistics_no', models.CharField(blank=True, default='', max_length=100, verbose_name='物流单号')),
                ('pickup_time', models.DateTimeField(blank=True, null=True, verbose_name='提货时间')),
                ('delivery_photos', models.JSONField(blank=True, default=list, verbose_name='派送图片')),
                ('city', models.CharField(blank=True, default='', max_length=50, verbose_name='城市')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_operations', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '产品流转仓',
                'verbose_name_plural': '产品流转仓',
                'db_table': 'warehouse_products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WarehouseTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_city', models.CharField(max_length=50, verbose_name='调出城市')),
                ('to_city', models.CharField(max_length=50, verbose_name='调入城市')),
                ('goods_info', models.TextField(blank=True, default='', verbose_name='调拨货品信息')),
                ('status', models.CharField(default='pending', help_text='pending/confirmed/transit/completed', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_confirmed', to=settings.AUTH_USER_MODEL, verbose_name='确认人')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers_initiated', to=settings.AUTH_USER_MODEL, verbose_name='发起人')),
            ],
            options={
                'verbose_name': '城市间调拨',
                'verbose_name_plural': '城市间调拨',
                'db_table': 'warehouse_transfers',
                'ordering': ['-created_at'],
            },
        ),
    ]
