# Generated by Django 5.2.13 on 2026-04-12 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_customer_phone_and_more'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseproduct',
            name='auto_generated',
            field=models.BooleanField(default=False, verbose_name='自动生成'),
        ),
        migrations.AddField(
            model_name='warehouseproduct',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouse_products', to='orders.order', verbose_name='关联订单'),
        ),
        migrations.AddField(
            model_name='warehouseproduct',
            name='order_status',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='订单状态'),
        ),
    ]
