# -*- coding: utf-8 -*-

# Generated by Django 5.2.13 on 2026-04-12 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_customer_phone_and_more'),
        ('warehouse', '0002_warehouseproduct_auto_generated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseproduct',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='warehouse_products', to='orders.order', verbose_name='关联订单'),
        ),
    ]
