# Generated by Django 5.2.13 on 2026-04-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_warehouseproduct_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessoryinventory',
            name='stock_records',
            field=models.JSONField(blank=True, default=list, help_text='[{"type": "out", "quantity": 10, "reason": "安装使用", "operator": "admin", "created_at": "..."}]', verbose_name='出入库记录'),
        ),
        migrations.AddField(
            model_name='hardwareinventory',
            name='stock_records',
            field=models.JSONField(blank=True, default=list, help_text='[{"type": "out", "quantity": 10, "reason": "安装使用", "operator": "admin", "created_at": "..."}]', verbose_name='出入库记录'),
        ),
    ]
