# -*- coding: utf-8 -*-

# Generated by Django 5.2.13 on 2026-04-22 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_accessoryinventory_stock_records_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessoryinventory',
            name='stock_records',
        ),
        migrations.RemoveField(
            model_name='hardwareinventory',
            name='stock_records',
        ),
        migrations.CreateModel(
            name='StockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('hardware', '五金'), ('accessory', '配件')], max_length=20, verbose_name='物品类型')),
                ('item_id', models.IntegerField(verbose_name='物品ID')),
                ('record_type', models.CharField(choices=[('in', '入库'), ('out', '出库')], max_length=10, verbose_name='记录类型')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('reason', models.TextField(blank=True, default='', verbose_name='原因')),
                ('related_task_id', models.CharField(blank=True, default='', max_length=50, verbose_name='关联任务ID')),
                ('supplier', models.CharField(blank=True, default='', max_length=200, verbose_name='供应商')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '出入库记录',
                'verbose_name_plural': '出入库记录',
                'db_table': 'stock_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
