# Generated by Django 5.2.13 on 2026-04-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_remove_accessoryinventory_stock_records_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouseproduct',
            name='city',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='warehouseproduct',
            name='product_type',
            field=models.CharField(db_index=True, help_text='木门/合金门/防盗门', max_length=20, verbose_name='产品类型'),
        ),
        migrations.AlterField(
            model_name='warehouseproduct',
            name='status',
            field=models.CharField(choices=[('pending_ship', '待发货'), ('shipped', '已发货'), ('arrived', '已到货'), ('pending_deliver', '待派送'), ('delivered', '已派送')], db_index=True, default='pending_ship', max_length=20, verbose_name='状态'),
        ),
    ]
