# Generated by Django 5.2.12 on 2026-04-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_no', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='任务编号')),
                ('source', models.CharField(default='direct', help_text='brand_store/direct', max_length=20, verbose_name='来源')),
                ('customer_name', models.CharField(blank=True, default='', max_length=50, verbose_name='客户姓名')),
                ('customer_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='客户电话')),
                ('customer_address', models.CharField(max_length=500, verbose_name='客户地址')),
                ('product_details', models.JSONField(blank=True, default=list, help_text='按房间添加的产品信息', verbose_name='产品明细')),
                ('status', models.CharField(choices=[('pending', '待派单'), ('assigned', '已派单'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('site_photos', models.JSONField(blank=True, default=list, verbose_name='现场照片')),
                ('measurement_data', models.JSONField(blank=True, default=dict, verbose_name='测量数据')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('wage_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='工费')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '量尺任务',
                'verbose_name_plural': '量尺任务',
                'db_table': 'measurement_tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
