# Generated by Django 5.2.12 on 2026-04-05 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decoration', '0001_initial'),
        ('measurements', '0001_initial'),
        ('personnel', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementtask',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_measurements', to=settings.AUTH_USER_MODEL, verbose_name='派单人'),
        ),
        migrations.AddField(
            model_name='measurementtask',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurement_tasks', to='personnel.worker', verbose_name='量尺师傅'),
        ),
        migrations.AddField(
            model_name='measurementtask',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurement_tasks', to='users.branch', verbose_name='分公司'),
        ),
        migrations.AddField(
            model_name='measurementtask',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurement_tasks', to='decoration.brand', verbose_name='品牌'),
        ),
        migrations.AddField(
            model_name='measurementtask',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurement_requests', to='decoration.decorationstaff', verbose_name='申请人'),
        ),
        migrations.AddField(
            model_name='measurementtask',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurement_tasks', to='decoration.store', verbose_name='门店'),
        ),
    ]
