# -*- coding: utf-8 -*-

# Generated by Django 5.2.13 on 2026-04-12 17:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementtask',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='派单时间'),
        ),
        migrations.AddField(
            model_name='measurementtask',
            name='cancel_reason',
            field=models.TextField(blank=True, default='', verbose_name='取消原因'),
        ),
        migrations.AlterField(
            model_name='measurementtask',
            name='customer_phone',
            field=models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='请输入正确的11位手机号', regex='^1[3-9]\\d{9}$')], verbose_name='客户电话'),
        ),
    ]
