# Generated by Django 5.2.13 on 2026-04-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0003_measurementtask_assigned_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementtask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='measurementtask',
            name='source',
            field=models.CharField(db_index=True, default='direct', help_text='brand_store/direct', max_length=20, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='measurementtask',
            name='status',
            field=models.CharField(choices=[('pending', '待派单'), ('assigned', '已派单'), ('completed', '已完成'), ('cancelled', '已取消')], db_index=True, default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
