# -*- coding: utf-8 -*-

# Generated by Django 5.2.12 on 2026-04-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='订单编号')),
                ('source', models.CharField(choices=[('brand_store', '品牌门店'), ('direct', '直单'), ('direct_task', '直接任务')], max_length=20, verbose_name='来源')),
                ('order_type', models.CharField(choices=[('main', '主单'), ('supplement', '补单'), ('after_sale', '售后')], default='main', max_length=20, verbose_name='订单类型')),
                ('customer_name', models.CharField(blank=True, default='', max_length=50, verbose_name='客户姓名')),
                ('customer_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='客户电话')),
                ('customer_address', models.CharField(max_length=500, verbose_name='客户地址')),
                ('customer_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='客户售价')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, help_text='系统计算，付给工厂', max_digits=12, verbose_name='成本价')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('in_production', '生产中'), ('shipped', '已发货'), ('arrived', '已到货'), ('delivered', '已派送'), ('installing', '安装中'), ('completed', '已完成'), ('cancelled', '已取消'), ('closed', '已关闭')], default='pending', max_length=20, verbose_name='订单状态')),
                ('product_line', models.CharField(choices=[('wood', '木门'), ('alloy', '合金门'), ('security', '防盗门')], help_text='木门/合金门/防盗门', max_length=20, verbose_name='产品线')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_content', models.TextField(help_text='修改前→修改后', verbose_name='修改内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '订单修改日志',
                'verbose_name_plural': '订单修改日志',
                'db_table': 'order_change_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('wood', '木门'), ('alloy', '合金门'), ('security', '防盗门')], max_length=20, verbose_name='产品类型')),
                ('product_name', models.CharField(max_length=200, verbose_name='产品名称')),
                ('product_model', models.CharField(blank=True, default='', max_length=100, verbose_name='产品型号')),
                ('color', models.CharField(blank=True, default='', max_length=50, verbose_name='颜色')),
                ('specs', models.JSONField(blank=True, default=dict, help_text='每樘单独规格记录', verbose_name='规格参数')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('unit_cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='单位成本价')),
                ('hardware_items', models.JSONField(blank=True, default=list, help_text='五金名称+型号+数量', verbose_name='五金配件')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '订单明细',
                'verbose_name_plural': '订单明细',
                'db_table': 'order_items',
            },
        ),
    ]
