# -*- coding: utf-8 -*-

# Generated by Django 5.2.12 on 2026-04-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='salesman_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='导购姓名'),
        ),
        migrations.AddField(
            model_name='order',
            name='salesman_phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='导购电话'),
        ),
    ]
