# -*- coding: utf-8 -*-

# Generated by Django 5.2.13 on 2026-04-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_customer_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('produced', '已生产'), ('shipped', '已发货'), ('arrived', '已到货'), ('delivered', '已派送'), ('installing', '安装中'), ('completed', '已完成'), ('cancelled', '已取消'), ('closed', '已关闭')], default='pending', max_length=20, verbose_name='订单状态'),
        ),
    ]
