# Generated by Django 5.2.13 on 2026-04-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='市'),
        ),
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='区'),
        ),
        migrations.AddField(
            model_name='order',
            name='province',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='省'),
        ),
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('brand_store', '品牌门店'), ('direct', '直单'), ('direct_task', '直接任务'), ('direct_installation', '直接安装任务'), ('independent', '独立创建'), ('order', '从订单创建'), ('installation', '从安装单创建')], max_length=20, verbose_name='来源'),
        ),
    ]
