# Generated by Django 5.2.13 on 2026-04-22 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_add_province_city_district_to_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_address',
            field=models.CharField(db_index=True, max_length=500, verbose_name='客户地址'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='请输入正确的11位手机号', regex='^1[3-9]\\d{9}$')], verbose_name='客户电话'),
        ),
        migrations.AlterField(
            model_name='order',
            name='source',
            field=models.CharField(choices=[('brand_store', '品牌门店'), ('direct', '直单'), ('direct_task', '直接任务'), ('direct_installation', '直接安装任务'), ('independent', '独立创建'), ('order', '从订单创建'), ('installation', '从安装单创建')], db_index=True, max_length=20, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('produced', '已生产'), ('shipped', '已发货'), ('arrived', '已到货'), ('delivered', '已派送'), ('installing', '安装中'), ('completed', '已完成'), ('cancelled', '已取消'), ('closed', '已关闭')], db_index=True, default='pending', max_length=20, verbose_name='订单状态'),
        ),
    ]
