# Generated by Django 5.2.12 on 2026-04-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_no', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='任务编号')),
                ('source', models.CharField(choices=[('brand_store', '品牌门店'), ('direct', '直单'), ('direct_task', '直接任务')], default='brand_store', max_length=20, verbose_name='来源')),
                ('customer_name', models.CharField(blank=True, default='', max_length=50, verbose_name='客户姓名')),
                ('customer_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='客户电话')),
                ('customer_address', models.CharField(blank=True, default='', max_length=500, verbose_name='客户地址')),
                ('issue_description', models.TextField(verbose_name='问题描述')),
                ('site_photos', models.JSONField(blank=True, default=list, verbose_name='现场照片/视频')),
                ('issue_type', models.CharField(blank=True, default='', max_length=50, verbose_name='问题类型')),
                ('status', models.CharField(choices=[('pending', '待派单'), ('assigned', '已派单'), ('completed', '已完成'), ('cancelled', '已取消'), ('partial', '部分完成')], default='pending', max_length=20, verbose_name='状态')),
                ('responsibility', models.CharField(blank=True, choices=[('factory', '工厂'), ('logistics', '物流'), ('installation', '安装'), ('measurement', '量尺'), ('delivery', '送货'), ('site', '工地'), ('none', '无责任')], default='', max_length=20, verbose_name='责任判定')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('deduction_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='扣费金额')),
                ('maintenance_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='维修费用')),
                ('wage_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='维修工费')),
                ('completion_photos', models.JSONField(blank=True, default=list, verbose_name='完成照片')),
                ('resolution', models.TextField(blank=True, default='', verbose_name='解决方案')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '维修任务',
                'verbose_name_plural': '维修任务',
                'db_table': 'maintenance_tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
