# Generated by Django 5.2.13 on 2026-04-12 17:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0003_alter_installationtask_customer_phone'),
        ('maintenance', '0002_initial'),
        ('personnel', '0003_alter_foreman_phone_alter_worker_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancetask',
            name='accessory_reissue',
            field=models.BooleanField(default=False, verbose_name='是否补发配件'),
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='installation_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_tasks', to='installations.installationtask', verbose_name='关联安装单'),
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='installer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_installer_tasks', to='personnel.worker', verbose_name='安装人'),
        ),
        migrations.AddField(
            model_name='maintenancetask',
            name='reissue_items',
            field=models.JSONField(blank=True, default=list, verbose_name='补发配件明细'),
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='customer_phone',
            field=models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='请输入正确的11位手机号', regex='^1[3-9]\\d{9}$')], verbose_name='客户电话'),
        ),
    ]
