# Generated by Django 5.2.13 on 2026-04-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_maintenancetask_assigned_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancetask',
            name='issue_description',
            field=models.TextField(blank=True, default='', verbose_name='问题描述'),
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='source',
            field=models.CharField(choices=[('brand_store', '品牌门店'), ('direct', '直单'), ('direct_task', '直接任务'), ('independent', '独立创建'), ('order', '从订单创建'), ('installation', '从安装单创建')], default='brand_store', max_length=20, verbose_name='来源'),
        ),
    ]
