# Generated by Django 5.2.13 on 2026-04-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_add_accessory_reissue_reason_and_repair_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancetask',
            name='source',
            field=models.CharField(choices=[('brand_store', '品牌门店'), ('direct', '直单'), ('direct_task', '直接任务'), ('direct_installation', '直接安装任务'), ('independent', '独立创建'), ('order', '从订单创建'), ('installation', '从安装单创建')], default='brand_store', max_length=20, verbose_name='来源'),
        ),
    ]
