# Generated by Django 5.2.13 on 2026-04-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_alter_maintenancetask_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancetask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='responsibility',
            field=models.CharField(blank=True, choices=[('factory', '工厂'), ('logistics', '物流'), ('installation', '安装'), ('measurement', '量尺'), ('delivery', '送货'), ('site', '工地'), ('none', '无责任')], db_index=True, default='', max_length=20, verbose_name='责任判定'),
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='source',
            field=models.CharField(choices=[('brand_store', '品牌门店'), ('direct', '直单'), ('direct_task', '直接任务'), ('direct_installation', '直接安装任务'), ('independent', '独立创建'), ('order', '从订单创建'), ('installation', '从安装单创建')], db_index=True, default='brand_store', max_length=20, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='maintenancetask',
            name='status',
            field=models.CharField(choices=[('pending', '待派单'), ('assigned', '已派单'), ('completed', '已完成'), ('cancelled', '已取消'), ('partial', '部分完成')], db_index=True, default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
