# -*- coding: utf-8 -*-

# Generated by Django 5.2.12 on 2026-04-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractModeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_line', models.CharField(choices=[('wood', '木门'), ('alloy', '合金门'), ('security', '防盗门')], max_length=20, verbose_name='产品线')),
                ('contract_mode', models.CharField(choices=[('service_contractor', '服务承包商'), ('personal', '个人承包')], max_length=20, verbose_name='承包模式')),
                ('contractor_name', models.CharField(blank=True, default='', max_length=100, verbose_name='承包商名称')),
                ('settlement_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='承包结算价')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '承包模式设置',
                'verbose_name_plural': '承包模式设置',
                'db_table': 'contract_mode_settings',
            },
        ),
        migrations.CreateModel(
            name='Foreman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='手机号')),
                ('wechat', models.CharField(blank=True, default='', max_length=100, verbose_name='微信号')),
                ('bank_card_no', models.CharField(blank=True, default='', max_length=30, verbose_name='银行卡号')),
                ('city', models.CharField(blank=True, default='', max_length=50, verbose_name='城市')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='抽成比例(%)')),
                ('status', models.CharField(choices=[('active', '在职'), ('resigned', '离职'), ('disabled', '禁用')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '工头',
                'verbose_name_plural': '工头',
                'db_table': 'foremen',
            },
        ),
        migrations.CreateModel(
            name='WageSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='格式：YYYY-MM-01', verbose_name='结算月份')),
                ('measurement_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='量尺费')),
                ('installation_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='安装费')),
                ('maintenance_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='维修费')),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='送货费')),
                ('subsidy', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='补贴')),
                ('deduction', models.DecimalField(decimal_places=2, default=0, help_text='责任扣费等', max_digits=10, verbose_name='扣费')),
                ('total_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='总工费')),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('paid', '已支付')], default='pending', max_length=20, verbose_name='状态')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '月结算记录',
                'verbose_name_plural': '月结算记录',
                'db_table': 'wage_settlements',
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='WageStandard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('skill_type', models.CharField(choices=[('measurement', '量尺'), ('installation', '安装'), ('maintenance', '维修'), ('delivery', '送货')], max_length=20, verbose_name='技能类型')),
                ('billing_type', models.CharField(choices=[('per_time', '按次'), ('per_door', '按门数量'), ('per_piece', '按樘')], max_length=20, verbose_name='计费方式')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='单价')),
                ('product_line', models.CharField(blank=True, default='', help_text='安装/送货按产品细分', max_length=20, verbose_name='产品线细分')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认模板')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '工费标准',
                'verbose_name_plural': '工费标准',
                'db_table': 'wage_standards',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='手机号')),
                ('wechat', models.CharField(blank=True, default='', max_length=100, verbose_name='微信号')),
                ('bank_card_no', models.CharField(blank=True, default='', max_length=30, verbose_name='银行卡号')),
                ('skills', models.JSONField(default=list, help_text='量尺/安装/维修/送货多选', verbose_name='技能类型')),
                ('city', models.CharField(blank=True, default='', max_length=50, verbose_name='城市')),
                ('status', models.CharField(choices=[('active', '在职'), ('resigned', '离职'), ('disabled', '禁用')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '服务师傅',
                'verbose_name_plural': '服务师傅',
                'db_table': 'workers',
                'ordering': ['-created_at'],
            },
        ),
    ]
