# Generated by Django 5.2.12 on 2026-04-05 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contractmodesetting',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_settings', to='users.branch', verbose_name='分公司'),
        ),
        migrations.AddField(
            model_name='foreman',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foremen', to='users.branch', verbose_name='分公司'),
        ),
        migrations.AddField(
            model_name='foreman',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foreman_profile', to=settings.AUTH_USER_MODEL, verbose_name='关联系统用户'),
        ),
        migrations.AddField(
            model_name='wagesettlement',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wage_confirmations', to=settings.AUTH_USER_MODEL, verbose_name='确认人'),
        ),
        migrations.AddField(
            model_name='wagestandard',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wage_standards', to='users.branch', verbose_name='分公司'),
        ),
        migrations.AddField(
            model_name='worker',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='users.branch', verbose_name='分公司'),
        ),
        migrations.AddField(
            model_name='worker',
            name='foreman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='personnel.foreman', verbose_name='工头归属'),
        ),
        migrations.AddField(
            model_name='worker',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_profile', to=settings.AUTH_USER_MODEL, verbose_name='关联系统用户'),
        ),
        migrations.AddField(
            model_name='worker',
            name='wage_standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='personnel.wagestandard', verbose_name='工费标准'),
        ),
        migrations.AddField(
            model_name='wagesettlement',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlements', to='personnel.worker', verbose_name='师傅'),
        ),
        migrations.AlterUniqueTogether(
            name='contractmodesetting',
            unique_together={('branch', 'product_line')},
        ),
        migrations.AlterUniqueTogether(
            name='wagesettlement',
            unique_together={('worker', 'month')},
        ),
    ]
