# -*- coding: utf-8 -*-

# Generated by Django 5.2.13 on 2026-04-12 17:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foreman',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='请输入正确的11位手机号', regex='^1[3-9]\\d{9}$')], verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='请输入正确的11位手机号', regex='^1[3-9]\\d{9}$')], verbose_name='手机号'),
        ),
    ]
