# Generated by Django 5.2.12 on 2026-04-06 12:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='角色名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_system', models.BooleanField(default=False, verbose_name='系统预设角色')),
                ('data_scope', models.CharField(choices=[('all', '全部数据'), ('city', '本城市数据'), ('department', '本部门数据'), ('self', '仅自己创建的数据')], default='all', max_length=20, verbose_name='数据范围')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'perm_roles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='菜单名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='菜单编码')),
                ('path', models.CharField(blank=True, max_length=200, verbose_name='路由路径')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='图标')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('menu_type', models.CharField(choices=[('menu', '菜单'), ('button', '按钮')], default='menu', max_length=10)),
                ('is_visible', models.BooleanField(default=True, verbose_name='是否显示')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='permissions.menu', verbose_name='父菜单')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
                'db_table': 'perm_menus',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PermissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50, verbose_name='操作类型')),
                ('target', models.CharField(blank=True, max_length=200, verbose_name='操作对象')),
                ('detail', models.JSONField(default=dict, verbose_name='变更详情')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '权限操作日志',
                'verbose_name_plural': '权限操作日志',
                'db_table': 'perm_permission_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoleFieldPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=50, verbose_name='应用标识')),
                ('model_name', models.CharField(max_length=50, verbose_name='模型名称')),
                ('field_name', models.CharField(max_length=50, verbose_name='字段名称')),
                ('visible', models.BooleanField(default=True, verbose_name='是否可见')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_permissions', to='permissions.role', verbose_name='角色')),
            ],
            options={
                'verbose_name': '角色字段权限',
                'verbose_name_plural': '角色字段权限',
                'db_table': 'perm_role_field_permissions',
                'unique_together': {('role', 'app_label', 'model_name', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='RoleMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='permissions.role', verbose_name='角色')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perm_roles', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '角色成员',
                'verbose_name_plural': '角色成员',
                'db_table': 'perm_role_members',
                'unique_together': {('role', 'user')},
            },
        ),
        migrations.CreateModel(
            name='RoleMenuPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='permissions.menu', verbose_name='菜单')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_permissions', to='permissions.role', verbose_name='角色')),
            ],
            options={
                'verbose_name': '角色菜单权限',
                'verbose_name_plural': '角色菜单权限',
                'db_table': 'perm_role_menu_permissions',
                'unique_together': {('role', 'menu')},
            },
        ),
    ]
