# Generated by Django 5.2.13 on 2026-04-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='code',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='角色代码'),
        ),
    ]
