# Generated by Django 5.2.12 on 2026-04-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_no', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='任务编号')),
                ('source', models.CharField(choices=[('brand_store', '品牌门店'), ('direct', '直单'), ('direct_task', '直接任务')], default='brand_store', help_text='订单自动生成/手动创建/直接安装', max_length=20, verbose_name='来源')),
                ('customer_name', models.CharField(blank=True, default='', max_length=50, verbose_name='客户姓名')),
                ('customer_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='客户电话')),
                ('customer_address', models.CharField(blank=True, default='', max_length=500, verbose_name='客户地址')),
                ('door_types', models.JSONField(blank=True, default=list, help_text='直接安装单填写', verbose_name='门种类')),
                ('door_quantity', models.IntegerField(default=0, verbose_name='门数量')),
                ('size_list', models.JSONField(blank=True, default=list, verbose_name='尺寸单')),
                ('status', models.CharField(choices=[('pending', '待派单'), ('assigned', '已派单'), ('completed', '已完成'), ('cancelled', '已取消'), ('partial', '部分完成')], default='pending', max_length=20, verbose_name='状态')),
                ('room_photos', models.JSONField(blank=True, default=list, verbose_name='按房间安装照片')),
                ('installed_quantity', models.IntegerField(default=0, help_text='自动生成可改', verbose_name='安装数量')),
                ('additional_items', models.TextField(blank=True, default='', verbose_name='增项说明')),
                ('additional_fee', models.DecimalField(decimal_places=2, default=0, help_text='文员/后台填写', max_digits=10, verbose_name='增项费用')),
                ('subsidy', models.DecimalField(decimal_places=2, default=0, help_text='安装确认时填入，默认0', max_digits=10, verbose_name='补贴')),
                ('notes', models.TextField(blank=True, default='', verbose_name='备注')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('partial_next_type', models.CharField(blank=True, default='', help_text='售后/安装', max_length=20, verbose_name='部分完成后任务类型')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '安装任务',
                'verbose_name_plural': '安装任务',
                'db_table': 'installation_tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
