# Generated by Django 5.2.12 on 2026-04-05 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('decoration', '0001_initial'),
        ('installations', '0001_initial'),
        ('orders', '0001_initial'),
        ('personnel', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='installationtask',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_installations', to=settings.AUTH_USER_MODEL, verbose_name='派单人'),
        ),
        migrations.AddField(
            model_name='installationtask',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installation_tasks', to='users.branch', verbose_name='分公司'),
        ),
        migrations.AddField(
            model_name='installationtask',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installation_tasks', to='decoration.brand', verbose_name='品牌'),
        ),
        migrations.AddField(
            model_name='installationtask',
            name='installers',
            field=models.ManyToManyField(blank=True, related_name='installation_tasks', to='personnel.worker', verbose_name='安装师傅'),
        ),
        migrations.AddField(
            model_name='installationtask',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installation_tasks', to='orders.order', verbose_name='关联订单'),
        ),
        migrations.AddField(
            model_name='installationtask',
            name='parent_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_tasks', to='installations.installationtask', verbose_name='原任务'),
        ),
        migrations.AddField(
            model_name='installationtask',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_installations', to=settings.AUTH_USER_MODEL, verbose_name='审核人'),
        ),
        migrations.AddField(
            model_name='installationtask',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installation_tasks', to='decoration.store', verbose_name='门店'),
        ),
    ]
