# Generated by Django 5.2.13 on 2026-04-12 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installationtask',
            name='customer_phone',
            field=models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='请输入正确的11位手机号', regex='^1[3-9]\\d{9}$')], verbose_name='客户电话'),
        ),
    ]
