# -*- coding: utf-8 -*-

# Generated by Django 5.2.13 on 2026-04-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0003_alter_installationtask_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='installationtask',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='派单时间'),
        ),
        migrations.AddField(
            model_name='installationtask',
            name='cancel_reason',
            field=models.TextField(blank=True, default='', verbose_name='取消原因'),
        ),
    ]
