# Generated by Django 5.2.13 on 2026-04-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0004_installationtask_assigned_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installationtask',
            name='source',
            field=models.CharField(choices=[('brand_store', '品牌门店'), ('direct', '直单'), ('direct_task', '直接任务'), ('direct_installation', '直接安装任务'), ('independent', '独立创建'), ('order', '从订单创建'), ('installation', '从安装单创建')], default='brand_store', help_text='订单自动生成/手动创建/直接安装', max_length=20, verbose_name='来源'),
        ),
        migrations.AlterField(
            model_name='installationtask',
            name='status',
            field=models.CharField(choices=[('pending', '待派单'), ('assigned', '已派单'), ('in_progress', '进行中'), ('completed', '已完成'), ('cancelled', '已取消'), ('partial', '部分完成')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
