# Generated by Django 5.2.12 on 2026-04-05 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='品牌名称')),
                ('contact_person', models.CharField(max_length=50, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='联系电话')),
                ('address', models.CharField(blank=True, default='', max_length=500, verbose_name='地址')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌',
                'db_table': 'brands',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='门店名称')),
                ('address', models.CharField(max_length=500, verbose_name='地址')),
                ('contact_person', models.CharField(blank=True, default='', max_length=50, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='联系电话')),
                ('city', models.CharField(max_length=50, verbose_name='区域/城市')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='decoration.brand', verbose_name='品牌')),
            ],
            options={
                'verbose_name': '门店',
                'verbose_name_plural': '门店',
                'db_table': 'stores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DecorationStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('phone', models.CharField(max_length=20, verbose_name='手机号')),
                ('wechat', models.CharField(blank=True, default='', max_length=100, verbose_name='微信号')),
                ('role', models.CharField(choices=[('project_manager', '项目经理'), ('sales_guide', '导购'), ('clerk', '装企文员')], max_length=20, verbose_name='角色')),
                ('status', models.CharField(choices=[('active', '启用'), ('inactive', '停用')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='decoration.store', verbose_name='门店')),
            ],
            options={
                'verbose_name': '装企人员',
                'verbose_name_plural': '装企人员',
                'db_table': 'decoration_staff',
                'ordering': ['-created_at'],
            },
        ),
    ]
