# Generated by Django 5.2.12 on 2026-04-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decoration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='address',
        ),
        migrations.RemoveField(
            model_name='store',
            name='city',
        ),
        migrations.RemoveField(
            model_name='store',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='store',
            name='phone',
        ),
        migrations.AlterField(
            model_name='brand',
            name='contact_person',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='联系人'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='status',
            field=models.CharField(choices=[('cooperating', '合作中'), ('paused', '已暂停'), ('terminated', '已终止')], default='cooperating', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='decorationstaff',
            name='role',
            field=models.CharField(choices=[('project_manager', '项目经理'), ('sales_guide', '导购')], max_length=20, verbose_name='角色'),
        ),
        migrations.AlterField(
            model_name='decorationstaff',
            name='status',
            field=models.CharField(choices=[('cooperating', '合作中'), ('paused', '已暂停'), ('terminated', '已终止')], default='cooperating', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.CharField(choices=[('cooperating', '合作中'), ('paused', '已暂停'), ('terminated', '已终止')], default='cooperating', max_length=20, verbose_name='状态'),
        ),
    ]
