# Generated by Django 5.2.13 on 2026-04-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decoration', '0002_remove_brand_address_remove_store_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='process_order',
            field=models.CharField(choices=[('measure_first', '先量尺后下单'), ('order_first', '先下单后量尺')], default='measure_first', max_length=20, verbose_name='流程顺序'),
        ),
    ]
