# Generated by Django 5.2.13 on 2026-04-22 09:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decoration', '0003_brand_process_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_phone_or_landline', message='请输入正确的电话号码', regex='^(1[3-9]\\d{9}|0\\d{2,3}-?\\d{7,8})$')], verbose_name='联系电话'),
        ),
        migrations.AlterField(
            model_name='decorationstaff',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='请输入正确的11位手机号', regex='^1[3-9]\\d{9}$')], verbose_name='手机号'),
        ),
    ]
