# -*- coding: utf-8 -*-

# Generated by Django 5.2.12 on 2026-04-05 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='产品线名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='产品线代码')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '产品线分类',
                'verbose_name_plural': '产品线分类',
                'db_table': 'product_categories',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='厂家名称')),
                ('product_type', models.CharField(choices=[('wood', '木门'), ('alloy', '合金门'), ('security', '防盗门')], max_length=20, verbose_name='产品类型')),
                ('contact_person', models.CharField(blank=True, default='', max_length=50, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='联系电话')),
                ('address', models.CharField(blank=True, default='', max_length=500, verbose_name='地址')),
                ('status', models.CharField(choices=[('active', '在售'), ('inactive', '停售')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '供货厂家',
                'verbose_name_plural': '供货厂家',
                'db_table': 'suppliers',
            },
        ),
        migrations.CreateModel(
            name='SecurityProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='产品名称')),
                ('model', models.CharField(max_length=100, verbose_name='型号')),
                ('door_colors', models.JSONField(blank=True, default=list, help_text='可选多选', verbose_name='门扇颜色')),
                ('open_method', models.CharField(choices=[('single', '单开'), ('double', '双开')], max_length=20, verbose_name='开启方式')),
                ('open_direction', models.CharField(blank=True, choices=[('outer_left', '外左'), ('outer_right', '外右'), ('inner_left', '内左'), ('inner_right', '内右')], default='', max_length=20, verbose_name='开门方向')),
                ('size_type', models.CharField(choices=[('standard', '标尺'), ('custom', '定制')], max_length=20, verbose_name='尺寸类型')),
                ('standard_sizes', models.JSONField(blank=True, default=list, help_text='标尺时可用尺寸', verbose_name='标尺尺寸列表')),
                ('frame_type', models.CharField(blank=True, default='', max_length=100, verbose_name='门框类型')),
                ('fixed_config', models.JSONField(blank=True, default=dict, help_text='门板材质/表面处理/铰链/填充/密封条/门槛等', verbose_name='固定配置')),
                ('smart_lock_upcharge', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='智能锁补差价')),
                ('standard_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='标尺价')),
                ('custom_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='定制价')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/security/', verbose_name='产品图片')),
                ('special_craft_note', models.TextField(blank=True, default='', verbose_name='特殊工艺备注')),
                ('status', models.CharField(choices=[('active', '在售'), ('inactive', '停售')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_products', to='products.supplier', verbose_name='供货厂家')),
            ],
            options={
                'verbose_name': '防盗门产品',
                'verbose_name_plural': '防盗门产品',
                'db_table': 'security_products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='五金名称')),
                ('hardware_type', models.CharField(choices=[('lock', '锁具'), ('hinge', '合页'), ('other', '其他')], max_length=20, verbose_name='类型')),
                ('sub_type', models.CharField(blank=True, choices=[('mechanical_lock', '机械锁'), ('smart_lock', '智能锁'), ('mother_child_hinge', '子母合页'), ('other', '其他')], default='', max_length=30, verbose_name='子类型')),
                ('model', models.CharField(blank=True, default='', max_length=100, verbose_name='型号')),
                ('applicable_products', models.JSONField(blank=True, default=list, help_text='木门/合金门/防盗门多选', verbose_name='适用产品')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='成本价')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/hardware/', verbose_name='产品图片')),
                ('status', models.CharField(choices=[('active', '在售'), ('inactive', '停售')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hardware_items', to='products.supplier', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '五金配件',
                'verbose_name_plural': '五金配件',
                'db_table': 'hardware',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlloyProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='产品名称')),
                ('open_method', models.CharField(choices=[('swing', '平开门'), ('single_slide', '单推'), ('double_slide', '双推'), ('triple_slide', '三推')], max_length=20, verbose_name='开启方式')),
                ('track_type', models.CharField(blank=True, choices=[('overhead', '吊轨'), ('floor', '地轨')], default='', max_length=20, verbose_name='轨道类型')),
                ('profile', models.CharField(blank=True, default='', max_length=100, verbose_name='型材')),
                ('colors', models.JSONField(blank=True, default=list, verbose_name='颜色')),
                ('glass_type', models.CharField(blank=True, choices=[('single', '单玻'), ('double', '双玻')], default='', max_length=20, verbose_name='玻璃类型')),
                ('glass_kind', models.CharField(blank=True, default='', max_length=100, verbose_name='玻璃种类')),
                ('pricing_method', models.CharField(blank=True, default='', max_length=20, verbose_name='计价方式')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='单价（平方）')),
                ('oversize_fee', models.DecimalField(decimal_places=2, default=0, help_text='按供货厂家设置', max_digits=12, verbose_name='超尺费')),
                ('oversize_rule', models.TextField(blank=True, default='', verbose_name='超尺费规则')),
                ('glass_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='玻璃价格')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/alloy/', verbose_name='产品图片')),
                ('status', models.CharField(choices=[('active', '在售'), ('inactive', '停售')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alloy_products', to='products.supplier', verbose_name='供货厂家')),
            ],
            options={
                'verbose_name': '合金门产品',
                'verbose_name_plural': '合金门产品',
                'db_table': 'alloy_products',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WoodProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='产品名称')),
                ('surface_process', models.CharField(choices=[('paint', '油漆'), ('bare', '免漆')], max_length=20, verbose_name='表面工艺')),
                ('model', models.CharField(blank=True, default='', max_length=100, verbose_name='型号')),
                ('colors', models.JSONField(blank=True, default=list, help_text='多选，如["白色","原木色"]', verbose_name='颜色')),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='成本价')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/wood/', verbose_name='产品图片')),
                ('status', models.CharField(choices=[('active', '在售'), ('inactive', '停售')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wood_products', to='products.supplier', verbose_name='供货厂家')),
            ],
            options={
                'verbose_name': '木门产品',
                'verbose_name_plural': '木门产品',
                'db_table': 'wood_products',
                'ordering': ['-created_at'],
            },
        ),
    ]
