# -*- coding: utf-8 -*-

# Generated by Django 5.2.12 on 2026-04-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alloyproduct',
            name='status',
            field=models.CharField(choices=[('on_sale', '在售'), ('off_sale', '停售'), ('pre_sale', '预售')], default='on_sale', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='status',
            field=models.CharField(choices=[('on_sale', '在售'), ('off_sale', '停售'), ('pre_sale', '预售')], default='on_sale', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='securityproduct',
            name='status',
            field=models.CharField(choices=[('on_sale', '在售'), ('off_sale', '停售'), ('pre_sale', '预售')], default='on_sale', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='status',
            field=models.CharField(choices=[('on_sale', '在售'), ('off_sale', '停售'), ('pre_sale', '预售')], default='on_sale', max_length=20, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='woodproduct',
            name='status',
            field=models.CharField(choices=[('on_sale', '在售'), ('off_sale', '停售'), ('pre_sale', '预售')], default='on_sale', max_length=20, verbose_name='状态'),
        ),
    ]
